import fs from 'node:fs';
import path from 'node:path';
import { buildDownloadArgs, outputTemplate } from '../../core/ytdlpArgs';
import { friendlyYtdlpError, isCookieReadError, parseYtdlpLine, postprocessLabel } from '../../core/progress';
import { browserCookiesUnreadable, markBrowserCookiesUnreadable } from '../cookieHealth';
import { parseExtraArgs, speedLimitActive } from '../../shared/settings';
import { killTree, onLines, spawnTool } from '../process';
import { tools } from '../tools';
import { settings } from '../settings';
import { archiveFile } from '../paths';
import { requestContext } from '../request';
import { matchTracks } from '../services/ytmusic';
import { logger } from '../log';
import { postprocess } from './postprocess';
import type { Runner } from './queue';

const log = logger('ytdlp');

export const ytdlpRunner: Runner = (ctx) => {
  const job = ctx.job();
  const s = settings.get();
  let child: ReturnType<typeof spawnTool> | null = null;
  let stopped: 'pause' | 'cancel' | null = null;
  const cancels = new Set<() => void>();

  const isPlaylist = job.source.sourceKind === 'playlist';
  // Tracks from Spotify are matched to YouTube Music first, then downloaded as a list of URLs.
  const needsMatching = isPlaylist && job.source.entries.some((e) => e.match);
  const chosenEntries = job.options.playlistItems.length
    ? job.source.entries.filter((e) => job.options.playlistItems.includes(e.index))
    : job.source.entries;

  let outputDir = job.options.targetDir || job.outputDir || s.storage.otherDir;
  let template = outputTemplate(job.options, isPlaylist, s.downloads.playlistNumbering, s.downloads.filenameTemplate, {
    music: s.downloads.musicLayout, video: s.downloads.videoLayout,
  });
  if (needsMatching) {
    outputDir = path.join(outputDir, job.title.replace(/[\\/:*?"<>|]/g, '_').replace(/[. ]+$/, '').slice(0, 120) || 'Playlist');
    template = `${s.downloads.playlistNumbering ? '%(autonumber)02d - ' : ''}%(title)s.%(ext)s`;
  }
  fs.mkdirSync(outputDir, { recursive: true });
  ctx.patch({ outputDir });

  const { args: extraArgs } = parseExtraArgs(s.advanced.extraYtdlpArgs);
  const buildArgs = (opts: { batchFile?: string; browserCookies: boolean }) => buildDownloadArgs({
    url: job.url, batchFile: opts.batchFile, options: job.options, outputDir, tempDir: ctx.workDir, outputTemplate: template,
    ffmpegDir: tools.ffmpegDir(), jsRuntime: tools.jsRuntime(),
    archiveFile: isPlaylist && s.downloads.skipExisting ? archiveFile() : null,
    isPlaylist: isPlaylist && !needsMatching,
    request: requestContext(job.source.request, ctx.workDir, { withBrowserCookies: opts.browserCookies }),
    speedLimitKbps: speedLimitActive(s) ? s.downloads.speedLimitKbps : 0,
    retries: s.downloads.retries,
    concurrentFragments: s.downloads.concurrentFragments,
    sponsorBlock: s.downloads.sponsorBlock,
    sponsorCategories: s.downloads.sponsorCategories,
    embedThumbnail: s.downloads.embedThumbnail,
    squareMusicArtwork: s.downloads.squareMusicArtwork,
    includeAutoSubs: s.subtitles.includeAutoGenerated,
    windowsFilenames: process.platform === 'win32',
    extraArgs,
  });

  // Progress model: each item has one or two stream downloads (video then audio).
  const streamsPerItem = job.options.format.kind === 'video' ? 2 : 1;
  let itemsSeen = 0;
  let itemCount = isPlaylist ? chosenEntries.length || 1 : 1;
  let itemIndex = 0;
  let streamIndex = 0;
  let lastFraction = 0;
  const outputs: string[] = [...job.outputPaths];
  let errors: string[] = [];
  let stderrTail = '';

  const overall = (fraction: number) => {
    const itemFraction = Math.min(1, (streamIndex + fraction) / streamsPerItem);
    return Math.min(99, (100 * (itemIndex + itemFraction)) / Math.max(1, itemCount));
  };

  const handleLine = (line: string) => {
    const ev = parseYtdlpLine(line);
    if (!ev) {
      if (/^(ERROR|WARNING):/.test(line)) stderrTail = `${stderrTail}\n${line}`.slice(-6000);
      return;
    }
    switch (ev.type) {
      case 'item': {
        // Count items as they start; playlist_index can skip numbers when items are selected.
        itemsSeen++;
        itemIndex = itemsSeen - 1;
        if (ev.count && !job.options.playlistItems.length && !needsMatching) itemCount = ev.count;
        streamIndex = 0;
        lastFraction = 0;
        if (itemCount > 1) {
          ctx.progress({ item: { index: Math.min(itemsSeen, itemCount), count: itemCount, title: ev.title }, stage: ev.title }, 'running');
        }
        break;
      }
      case 'progress': {
        if (ev.status === 'finished') {
          streamIndex = Math.min(streamsPerItem - 1, streamIndex + 1);
          lastFraction = 0;
          return;
        }
        const fraction = ev.total ? ev.downloaded! / ev.total : ev.fragment ? ev.fragment[0] / ev.fragment[1] : lastFraction;
        lastFraction = fraction;
        ctx.progress({
          percent: overall(fraction), speedBps: ev.speed, etaSec: ev.eta, downloadedBytes: ev.downloaded, totalBytes: ev.total,
          stage: itemCount > 1 ? ctx.job().progress.item?.title ?? 'Downloading' : streamsPerItem === 2 ? (streamIndex === 0 ? 'Downloading video' : 'Downloading audio') : 'Downloading',
        }, 'running');
        break;
      }
      case 'postprocess':
        if (ev.status === 'started') ctx.progress({ stage: postprocessLabel(ev.name), speedBps: null, etaSec: null }, 'running');
        break;
      case 'file':
        outputs.push(ev.path);
        ctx.patch({ outputPaths: [...outputs], engineState: { ...ctx.job().engineState, finishedItems: outputs.length } });
        break;
      case 'error':
        errors.push(ev.message);
        break;
    }
  };

  const run = (opts: { batchFile?: string; browserCookies: boolean }) => {
    log.info(`Starting ${job.title}${opts.browserCookies ? '' : ' (without browser cookies)'}`);
    errors = [];
    stderrTail = '';
    child = spawnTool(tools.require('yt-dlp'), buildArgs(opts), { env: tools.env(), cwd: outputDir });
    onLines(child.stdout, handleLine);
    onLines(child.stderr, handleLine);
    child.on('error', (err) => ctx.fail(`Could not start yt-dlp: ${err.message}`));
    child.on('close', async (code) => {
      child = null;
      if (stopped) return;
      const allErrors = `${errors.join('\n')}\n${stderrTail}`;

      // A locked or encrypted browser cookie store shouldn't sink public downloads: retry once without it.
      if (code !== 0 && opts.browserCookies && isCookieReadError(allErrors) && !outputs.length) {
        markBrowserCookiesUnreadable();
        ctx.patch({ engineState: { ...ctx.job().engineState, cookieFallback: true } });
        ctx.progress({ stage: 'Couldn’t read browser cookies, retrying without them' }, 'running');
        run({ ...opts, browserCookies: false });
        return;
      }

      // Playlists: yt-dlp exits 1 if some items failed but others succeeded.
      const partial = isPlaylist && outputs.length > 0;
      if (code !== 0 && !partial) {
        const msg = errors.at(-1) ?? stderrTail.split('\n').filter(Boolean).at(-1) ?? `yt-dlp exited with code ${code}`;
        ctx.fail(friendlyYtdlpError(msg.replace(/^ERROR:\s*/, '')), stderrTail || errors.join('\n'));
        return;
      }
      if (!outputs.length && !(isPlaylist && s.downloads.skipExisting)) {
        ctx.fail('yt-dlp finished without producing a file.', stderrTail);
        return;
      }
      try {
        await postprocess(ctx, { register: (c) => cancels.add(c), stopped: () => stopped !== null });
        if (stopped) return;
        if (errors.length && partial) {
          ctx.patch({ compat: { ...(ctx.job().compat ?? { tvSafe: false }), summary: `${errors.length} item(s) could not be downloaded: ${friendlyYtdlpError(errors[0]!)}` } });
        }
        ctx.complete();
      } catch (err) {
        if (!stopped) ctx.fail(err instanceof Error ? err.message : String(err));
      }
    });
  };

  (async () => {
    let batchFile: string | undefined;
    if (needsMatching) {
      ctx.progress({ stage: `Finding songs on YouTube Music (0/${chosenEntries.length})`, percent: 0 }, 'running');
      const { urls, unmatched } = await matchTracks(
        chosenEntries.map((e) => e.match ?? { title: e.title, artist: e.uploader, durationSec: e.durationSec }),
        (done) => ctx.progress({ stage: `Finding songs on YouTube Music (${done}/${chosenEntries.length})` }, 'running'),
        () => stopped !== null,
      );
      if (stopped) return;
      if (unmatched) log.info(`${unmatched} of ${urls.length} tracks had no exact YouTube Music match; using search`);
      batchFile = path.join(ctx.workDir, 'batch.txt');
      fs.writeFileSync(batchFile, urls.join('\n'), 'utf8');
    }
    run({ batchFile, browserCookies: !browserCookiesUnreadable() });
  })().catch((err) => ctx.fail(err instanceof Error ? err.message : String(err)));

  return {
    stop: (reason) => {
      stopped = reason;
      killTree(child);
      for (const c of cancels) c();
    },
  };
};
