import { z } from 'zod';

export const PLAYER_THEMES = ['aurora', 'vinyl', 'pocket'] as const;
export type PlayerTheme = (typeof PLAYER_THEMES)[number];

export const SPONSOR_CATEGORIES = ['sponsor', 'selfpromo', 'interaction', 'intro', 'outro', 'preview', 'music_offtopic', 'filler'] as const;

const clampInt = (min: number, max: number, fallback: number) =>
  z.coerce.number().int().min(min).max(max).catch(fallback);
const clampNum = (min: number, max: number, fallback: number) =>
  z.coerce.number().min(min).max(max).catch(fallback);
const time = (fallback: string) => z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).catch(fallback);
const hexColor = (fallback: string) => z.string().regex(/^#[0-9a-fA-F]{6}$/).catch(fallback);

/** An object whose every field has a fallback, so a missing or partial section parses to defaults. */
const section = <T extends z.ZodRawShape>(shape: T) =>
  z.object(shape).prefault({} as z.input<z.ZodObject<T>>);

/**
 * Every setting has a default, so partial or outdated files always parse.
 * Paths default to empty strings and are filled from the OS in the main process.
 */
export const settingsSchema = z.object({
  version: z.literal(1).catch(1),

  general: section({
    startWithSystem: z.boolean().catch(false),
    startMode: z.enum(['downloader', 'player', 'last', 'tray']).catch('last'),
    closeToTray: z.boolean().catch(true),
    trayNoticeShown: z.boolean().catch(false),
    resumeQueue: z.boolean().catch(true),
    confirmQuitWithDownloads: z.boolean().catch(true),
    clipboardWatcher: z.boolean().catch(true),
    notifyOnComplete: z.boolean().catch(true),
    notifyOnFail: z.boolean().catch(true),
    completionSound: z.boolean().catch(false),
    whenQueueFinishes: z.enum(['nothing', 'sleep', 'shutdown']).catch('nothing'),
    globalShortcutEnabled: z.boolean().catch(true),
    globalShortcut: z.string().max(60).catch('CommandOrControl+Shift+D'),
    lastMode: z.enum(['downloader', 'player']).catch('downloader'),
  }),

  appearance: section({
    colorMode: z.enum(['system', 'dark', 'light']).catch('system'),
    accent: z.enum(['ember', 'iris', 'jade', 'sky', 'rose']).catch('ember'),
    uiScale: z.enum(['0.9', '1', '1.1', '1.25']).catch('1'),
    density: z.enum(['comfortable', 'compact']).catch('comfortable'),
    reducedMotion: z.enum(['system', 'on', 'off']).catch('system'),
    showSidebarStats: z.boolean().catch(true),
  }),

  downloads: section({
    concurrency: clampInt(1, 8, 3),
    concurrentFragments: clampInt(1, 16, 8),
    /** Use the bundled aria2 (many connections) for plain HTTP stream downloads — the big speed win on fast links. */
    accelerate: z.boolean().catch(true),
    speedLimitKbps: clampInt(0, 1_000_000, 0),
    speedLimitSchedule: section({
      enabled: z.boolean().catch(false),
      from: time('09:00'),
      to: time('18:00'),
    }),
    retries: clampInt(0, 10, 5),
    autoRetryFailed: z.boolean().catch(true),
    defaultPreset: section({
      music: z.string().catch('audio-original'),
      video: z.string().catch('video-source-max'),
      series: z.string().catch('video-1080'),
    }),
    filenameTemplate: z.string().min(1).max(200).catch('%(title)s'),
    musicLayout: z.enum(['flat', 'artist', 'artist-album']).catch('flat'),
    videoLayout: z.enum(['flat', 'channel']).catch('flat'),
    playlistNumbering: z.boolean().catch(true),
    writePlaylistFile: z.boolean().catch(true),
    skipExisting: z.boolean().catch(true),
    embedMetadata: z.boolean().catch(true),
    embedThumbnail: z.boolean().catch(true),
    squareMusicArtwork: z.boolean().catch(true),
    embedLyrics: z.boolean().catch(true),
    writeLrcFile: z.boolean().catch(false),
    sponsorBlock: z.enum(['off', 'mark', 'remove']).catch('off'),
    sponsorCategories: z.array(z.enum(SPONSOR_CATEGORIES)).catch(['sponsor', 'selfpromo', 'interaction']),
    preventSleep: z.boolean().catch(true),
    afterDownload: z.enum(['nothing', 'reveal']).catch('nothing'),
  }),

  formats: section({
    videoContainer: z.enum(['mkv', 'mp4']).catch('mp4'),
    mp3Bitrate: z.enum(['192', '256', '320']).catch('320'),
    hardwareEncoding: z.boolean().catch(true),
    encodeQuality: z.enum(['fast', 'balanced', 'quality']).catch('balanced'),
    keepOriginalAfterConvert: z.boolean().catch(false),
  }),

  subtitles: section({
    englishByDefault: z.boolean().catch(false),
    output: z.array(z.enum(['sidecar', 'embed', 'burn'])).catch(['sidecar', 'embed']),
    includeAutoGenerated: z.boolean().catch(true),
    whisperModel: z.enum(['base', 'small']).catch('base'),
    useGpu: z.boolean().catch(true),
    style: section({
      font: z.enum(['sans', 'serif', 'rounded', 'mono']).catch('sans'),
      size: clampNum(0.6, 2, 1),
      color: hexColor('#FFFFFF'),
      background: z.enum(['box', 'outline', 'shadow', 'none']).catch('outline'),
      backgroundOpacity: clampNum(0, 1, 0.55),
      bold: z.boolean().catch(false),
      position: z.enum(['bottom', 'top']).catch('bottom'),
    }),
  }),

  storage: section({
    musicDir: z.string().catch(''),
    videoDir: z.string().catch(''),
    seriesDir: z.string().catch(''),
    otherDir: z.string().catch(''),
    tempDir: z.string().catch(''),
    libraryRoots: z.array(z.string()).catch([]),
  }),

  library: section({
    watchFolders: z.boolean().catch(true),
    minAudioSeconds: clampInt(0, 600, 30),
    musicView: z.enum(['details', 'compact']).catch('details'),
    videoView: z.enum(['grid', 'list']).catch('grid'),
  }),

  player: section({
    theme: z.enum(PLAYER_THEMES).catch('aurora'),
    effects: z.enum(['balanced', 'still']).catch('balanced'),
    resumePosition: z.boolean().catch(true),
    volume: clampNum(0, 1, 0.8),
    autoOpenLyrics: z.boolean().catch(false),
    lyricsSize: z.enum(['small', 'medium', 'large']).catch('medium'),
    openPlayerOnPlay: z.boolean().catch(false),
    showKeyboardHints: z.boolean().catch(true),
    /** Empty = the system default audio output; otherwise a mediaDevices deviceId. */
    outputDeviceId: z.string().max(255).catch(''),
    eqEnabled: z.boolean().catch(false),
    /** A built-in profile id (see core/equalizer) or 'custom'. */
    eqProfile: z.string().max(40).catch('flat'),
    /** Custom band gains in dB (one per EQ band); only used when eqProfile === 'custom'. */
    eqBands: z.array(z.coerce.number().min(-12).max(12)).max(16).catch([0, 0, 0, 0, 0]),
  }),

  network: section({
    proxy: z.string().max(300).catch(''),
    cookiesFrom: z.enum(['none', 'lumina', 'file', 'chrome', 'edge', 'firefox', 'brave']).catch('none'),
    cookiesFile: z.string().catch(''),
    userAgent: z.string().max(400).catch(''),
    forceIpv4: z.boolean().catch(false),
    connectionsPerServer: clampInt(1, 16, 16),
  }),

  torrents: section({
    seedRatio: clampNum(0, 10, 0),
    seedMinutes: clampInt(0, 10_080, 0),
    listenPort: clampInt(1024, 65535, 6881),
    requireEncryption: z.boolean().catch(false),
    maxPeers: clampInt(10, 500, 120),
    uploadLimitKbps: clampInt(0, 1_000_000, 0),
    dht: z.boolean().catch(true),
    autoTrackers: z.boolean().catch(true),
  }),

  extension: section({
    enabled: z.boolean().catch(true),
    port: clampInt(1024, 65535, 17865),
    captureDownloads: z.boolean().catch(true),
    /** auto: start straight away in the background; ask: open Lumina to choose. */
    browserDownloads: z.enum(['auto', 'ask']).catch('auto'),
    minCaptureSizeMb: clampInt(0, 10_000, 0),
    /** Empty = the system Downloads folder, where people expect browser downloads. */
    saveDir: z.string().catch(''),
    skipExtensions: z.array(z.string().regex(/^[a-z0-9]{1,10}$/)).max(100).catch([]),
    skipSites: z.array(z.string().max(253)).max(200).catch([]),
  }),

  accounts: section({
    spotifyClientId: z.string().regex(/^([0-9a-f]{32})?$/).catch(''),
  }),

  privacy: section({
    keepHistory: z.boolean().catch(true),
    historyDays: clampInt(0, 3650, 0),
  }),

  updates: section({
    autoUpdateYtdlp: z.boolean().catch(true),
    ytdlpChannel: z.enum(['stable', 'nightly']).catch('stable'),
    lastYtdlpCheck: z.number().catch(0),
  }),

  sync: section({
    /** Folder holding the encrypted lumina-sync.bin both devices reach (USB / shared / cloud-drive folder). */
    folder: z.string().max(1024).catch(''),
    /** A friendly name for this device shown in the chain (defaults to the hostname in the main process). */
    deviceLabel: z.string().max(60).catch(''),
    /** Sync bookmarks across the chain. More record types (likes, history) toggle in as they land. */
    syncBookmarks: z.boolean().catch(true),
  }),

  advanced: section({
    customToolPaths: z.record(z.string(), z.string()).catch({}),
    verboseLogs: z.boolean().catch(false),
    extraYtdlpArgs: z.string().max(1000).catch(''),
  }),
});

export type Settings = z.infer<typeof settingsSchema>;
export type SettingsSection = keyof Omit<Settings, 'version'>;

/** Deep-partial patch accepted by settings:update. */
export type SettingsPatch = { [K in SettingsSection]?: Partial<Settings[K]> };

export const defaultSettings = (): Settings => settingsSchema.parse({});

export function mergeSettings(current: Settings, patch: SettingsPatch): Settings {
  const next: Record<string, unknown> = { ...current };
  for (const [key, values] of Object.entries(patch)) {
    if (!values || key === 'version') continue;
    next[key] = { ...(current as unknown as Record<string, object>)[key], ...values };
  }
  return settingsSchema.parse(next);
}

/** yt-dlp options that could run programs or change where Lumina reads config or writes files. */
const BLOCKED_ARGS = /^--?(exec|exec-before-download|batch-file|a|config-location|config-locations|plugin-dirs|load-info-json|output|o|paths|P|ffmpeg-location|downloader|external-downloader|downloader-args|external-downloader-args|print-to-file|update|update-to|U|cookies|cookies-from-browser)(=|$)/;

/** Split a user-typed argument string, respecting quotes. Blocked options return an error. */
export function parseExtraArgs(input: string): { args: string[]; error: string | null } {
  const args: string[] = [];
  for (const m of input.matchAll(/"([^"]*)"|'([^']*)'|(\S+)/g)) args.push(m[1] ?? m[2] ?? m[3] ?? '');
  const blocked = args.find((a) => BLOCKED_ARGS.test(a));
  return blocked
    ? { args: [], error: `“${blocked}” isn’t allowed here because it can run programs or change file locations.` }
    : { args, error: null };
}

/** Whether the speed limit applies at this moment (always, or only inside the scheduled window). */
export function speedLimitActive(s: Settings, now = new Date()): boolean {
  if (s.downloads.speedLimitKbps <= 0) return false;
  const sch = s.downloads.speedLimitSchedule;
  if (!sch.enabled) return true;
  const minutes = now.getHours() * 60 + now.getMinutes();
  const toMinutes = (t: string) => Number(t.slice(0, 2)) * 60 + Number(t.slice(3, 5));
  const from = toMinutes(sch.from);
  const to = toMinutes(sch.to);
  return from <= to ? minutes >= from && minutes < to : minutes >= from || minutes < to;
}
